/**
 * house-colors.template.ts — the palette for the login shell, rendered to
 * house-colors.sh.
 *
 * The file exports LS_COLORS and touches nothing else, so a shell sources it and
 * keeps its own settings. GNU ls wants a colour as an SGR sequence, not as a hex
 * string: a `#rrggbb` value is passed through to the terminal verbatim and
 * colours nothing, so every entry here is the 24-bit form `38;2;r;g;b`, built
 * from the token's channels.
 *
 * The output is sourced rather than executed, so it carries no shebang: a
 * shellcheck directive naming bash stands in for one, because the linter
 * carries no zsh dialect and its other dialects would refuse syntax this shell
 * accepts.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  colour: { parseHex(hex: string): { r: number; g: number; b: number } }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    "# shellcheck shell=bash",
    "# A fragment the login shell sources, never a script it runs: shellcheck has",
    "# no zsh dialect, so the directive above names the kind it can read.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template house-colors.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ].join("\n")
}

function sgr(context: Context, name: string): string {
  const token = context.palette.find(name)
  const value = token.solid ?? token.hex
  if (value === undefined) throw new Error(`${name} carries no colour`)
  const { r, g, b } = context.colour.parseHex(value)
  return `38;2;${r};${g};${b}`
}

const CLASSES: [string, string][] = [
  ["di", "accent.primary"],
  ["ln", "accent.secondary"],
  ["pi", "accent.tertiary"],
  ["so", "state.success"],
  ["bd", "state.warning"],
  ["cd", "state.warning"],
  ["or", "text.faint-solid"],
  ["ex", "state.success"],
  ["do", "accent.tertiary"],
  ["su", "state.error"],
  ["sg", "state.error"],
  ["tw", "accent.soft"],
  ["ow", "accent.soft"],
  ["st", "accent.soft"],
  ["mi", "state.error"],
  ["rs", "text.primary"],
  ["fi", "text.primary"],
]

const SUFFIXES: [string, string][] = [
  ["*.md", "text.secondary"],
  ["*.json", "state.warning"],
  ["*.toml", "state.warning"],
  ["*.yaml", "state.warning"],
  ["*.yml", "state.warning"],
  ["*.css", "accent.secondary"],
  ["*.ts", "accent.primary"],
  ["*.tsx", "accent.primary"],
  ["*.js", "state.warning"],
  ["*.sh", "state.success"],
  ["*.lock", "text.faint-solid"],
]

export default {
  render(context: Context): string {
    const entries = [...CLASSES, ...SUFFIXES].map(([key, token]) => `${key}=${sgr(context, token)}`)
    return `${header(context)}LS_COLORS="${entries.join(":")}"\nexport LS_COLORS\n`
  },
}
