# Generated by house-palette from the house palette — do not edit by hand.
# shellcheck shell=bash
# A fragment the login shell sources, never a script it runs: shellcheck has
# no zsh dialect, so the directive above names the kind it can read.
# palette 04031d0, sha256 15322952c371949710ae4648cc4e1feb64c5ff750451bc8f85113e1aa3b2127a
# template house-colors.template.ts, sha256 a06b78fc3e3ff7d15230c235aec0f31ef6d7fab988406dccf365a7fce93640ba
# Re-render with .github/scripts/palette-check.sh --render; see the README.
LS_COLORS="di=38;2;138;181;247:ln=38;2;76;204;242:pi=38;2;184;140;242:so=38;2;138;247;174:bd=38;2;240;179;90:cd=38;2;240;179;90:or=38;2;96;97;99:ex=38;2;138;247;174:do=38;2;184;140;242:su=38;2;255;107;107:sg=38;2;255;107;107:tw=38;2;173;203;249:ow=38;2;173;203;249:st=38;2;173;203;249:mi=38;2;255;107;107:rs=38;2;230;230;230:fi=38;2;230;230;230:*.md=38;2;201;201;201:*.json=38;2;240;179;90:*.toml=38;2;240;179;90:*.yaml=38;2;240;179;90:*.yml=38;2;240;179;90:*.css=38;2;76;204;242:*.ts=38;2;138;181;247:*.tsx=38;2;138;181;247:*.js=38;2;240;179;90:*.sh=38;2;138;247;174:*.lock=38;2;96;97;99"
export LS_COLORS
