/**
 * kdeglobals.colours.template.ts — the desktop environment's colours, rendered
 * to kdeglobals.colours.ini.
 *
 * The KDE INI format has no include, so this file is a fragment rather than a
 * file any program reads: an edit of the live kdeglobals merges these sections
 * into it and leaves every other section alone. The format carries no alpha, so
 * every value is the token's solid form as an `R,G,B` triple.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  colour: { parseHex(hex: string): { r: number; g: number; b: number } }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template kdeglobals.colours.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "# KDE reads no include: the live kdeglobals is merged from these sections by hand.",
    "",
  ].join("\n")
}

function triple(context: Context, name: string): string {
  const token = context.palette.find(name)
  const value = token.solid ?? token.hex
  if (value === undefined) throw new Error(`${name} carries no colour`)
  const { r, g, b } = context.colour.parseHex(value)
  return `${r},${g},${b}`
}

/** The keys every surface of a KDE colour scheme carries, each mapped to the token that plays its part. */
const KEYS: [string, string][] = [
  ["ForegroundNormal", "text.primary"],
  ["ForegroundInactive", "text.faint-solid"],
  ["ForegroundActive", "accent.primary"],
  ["ForegroundLink", "accent.primary"],
  ["ForegroundVisited", "accent.tertiary"],
  ["ForegroundNegative", "state.error"],
  ["ForegroundNeutral", "state.warning"],
  ["ForegroundPositive", "state.success"],
  ["DecorationFocus", "accent.primary"],
  ["DecorationHover", "accent.soft"],
]

const SECTIONS: [string, [string, string][]][] = [
  [
    "Colors:Window",
    [
      ["BackgroundNormal", "surface.window"],
      ["BackgroundAlternate", "surface.base"],
      ...KEYS,
    ],
  ],
  [
    "Colors:View",
    [
      ["BackgroundNormal", "surface.view"],
      ["BackgroundAlternate", "surface.window"],
      ...KEYS,
    ],
  ],
  [
    "Colors:Button",
    [
      ["BackgroundNormal", "surface.raised"],
      ["BackgroundAlternate", "surface.window"],
      ...KEYS,
    ],
  ],
  [
    "Colors:Selection",
    [
      ["BackgroundNormal", "accent.primary"],
      ["BackgroundAlternate", "accent.soft"],
      ["ForegroundNormal", "text.on-accent"],
      ["ForegroundInactive", "text.secondary"],
      ["ForegroundActive", "text.strong"],
      ["ForegroundLink", "text.on-accent"],
      ["ForegroundVisited", "text.secondary"],
      ["ForegroundNegative", "state.error"],
      ["ForegroundNeutral", "state.warning"],
      ["ForegroundPositive", "state.success"],
      ["DecorationFocus", "accent.primary"],
      ["DecorationHover", "accent.soft"],
    ],
  ],
  [
    "Colors:Tooltip",
    [
      ["BackgroundNormal", "surface.raised"],
      ["BackgroundAlternate", "surface.window"],
      ...KEYS,
    ],
  ],
  [
    "Colors:Complementary",
    [
      ["BackgroundNormal", "surface.window"],
      ["BackgroundAlternate", "surface.base"],
      ...KEYS,
    ],
  ],
]

export default {
  render(context: Context): string {
    const lines = [header(context)]
    SECTIONS.forEach(([section, keys], index) => {
      lines.push(`[${section}]`)
      for (const [key, token] of keys) lines.push(`${key}=${triple(context, token)}`)
      if (index < SECTIONS.length - 1) lines.push("")
    })
    return `${lines.join("\n")}\n`
  },
}
