# Fonts
font_family      JetBrainsMono Nerd Font
font_size        11.0
disable_ligatures never

# Cursor
cursor_shape     beam
cursor_blink_interval 0.5

# Window
window_padding_width 8
hide_window_decorations yes
sync_to_monitor yes

# Scrollback
scrollback_lines 10000

# Behavior
confirm_os_window_close 0
shell_integration enabled
copy_on_select clipboard

# Kittens
allow_remote_control yes
clipboard_control write-clipboard read-clipboard

# Appearance
background_opacity 0.5
