/**
 * palette.house.template.ts — the terminal palette, rendered to palette.house.conf.
 *
 * kitty reads a secondary config through `include`, and a relative path there is
 * resolved against the directory of the file that includes it, so the fragment
 * sits beside kitty.conf. kitty addresses its sixteen colour slots by number and
 * the palette names them `terminal.0` … `terminal.15`, so the two map one to
 * one. `background_opacity` stays in kitty.conf: it is the one terminal value
 * the palette carries as an opacity rather than as a colour.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string[] {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template palette.house.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ]
}

function colour(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.hex === undefined) throw new Error(`${name} carries no colour`)
  return token.hex
}

function solidColour(context: Context, name: string): string {
  const token = context.palette.find(name)
  const value = token.solid ?? token.hex
  if (value === undefined) throw new Error(`${name} carries no colour`)
  return value
}

export default {
  render(context: Context): string {
    const lines = header(context)
    const slots = Array.from({ length: 16 }, (_, slot) => slot)
    const settings: [string, string][] = [
      ["background", colour(context, "surface.base")],
      ["foreground", colour(context, "text.primary")],
      ["cursor", colour(context, "accent.primary")],
      ["cursor_text_color", colour(context, "text.on-accent")],
      ["selection_background", solidColour(context, "interaction.selection-row")],
      ["selection_foreground", colour(context, "text.strong")],
      ["url_color", colour(context, "accent.primary")],
      ...slots.map((slot): [string, string] => [`color${slot}`, colour(context, `terminal.${slot}`)]),
    ]
    for (const [key, value] of settings) lines.push(`${key} ${value}`)
    return `${lines.join("\n")}\n`
  },
}
