/**
 * house.template.ts — the boot splash as the house palette, rendered to house.script.
 *
 * Nothing here is loaded from disk: the field is the window's own fill, the text comes from
 * plymouth's label plugin, and the progress line is a block glyph stretched to the width it
 * needs — so the theme owns no image file that could fall out of step with the
 * palette. A colour in this script is three 0..1 floats with no alpha of its own, so a
 * token's alpha travels on the sprite instead.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
	palette: { find(name: string): Token }
	provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

/**
 * The script draws in the framebuffer's pixels, so text is worth holding at the size the
 * display actually has: a screen twice as wide as the reference is given text twice as
 * large, rather than a wordmark that reads as a speck on a hidpi panel.
 */
const REFERENCE_WIDTH = 1440

/**
 * The face a glyph is drawn in, named rather than left to the plugin. The label plugin's own
 * default is Pango's "Sans 12", which on this machine resolves to a face that carries neither
 * the box-drawing nor the block glyphs, so a glyph named by codepoint comes back as the
 * missing-glyph box and loses its ink once the bar is scaled down to a few pixels. This is the
 * same family the menu font is generated from, so both boot screens are drawn in one face.
 */
const FACE = "JetBrainsMono Nerd Font 16"

/**
 * A glyph whose ink fills its own box, so the bar stays solid at two pixels tall. A line-drawing
 * glyph has ink only a couple of pixels of its box thick, and the scale to the bar's height
 * averages it away.
 */
const SOLID = "\u2588"

function hexOf(context: Context, name: string): string {
	const hex = context.palette.find(name).hex
	if (hex === undefined) throw new Error(`${name} carries no colour to paint with`)
	return hex
}

/** A token's colour as the three 0..1 floats the script paints with. */
function floats(context: Context, name: string): string {
	const hex = hexOf(context, name)
	const channels = [1, 3, 5].map((at) => Number.parseInt(hex.slice(at, at + 2), 16) / 255)
	return channels.map((value) => value.toFixed(6)).join(", ")
}

/** A token's alpha as the 0..1 float a sprite takes, opaque when it carries none. */
function alpha(context: Context, name: string): string {
	return (context.palette.find(name).alpha ?? 1).toFixed(6)
}

function header(context: Context): string {
	const { palette, template } = context.provenance
	return [
		"# Generated by colourway from the house palette — do not edit by hand.",
		`# palette ${palette.revision}, sha256 ${palette.sha256}`,
		`# template house.template.ts, sha256 ${template.sha256}`,
		"# Re-render with .github/scripts/palette-check.sh --render; see the README.",
		"",
	].join("\n")
}

export default {
	render(context: Context): string {
		const lines = [
			header(context),
			"# The framebuffer this script is drawing into, and the scale text is held at.",
			"screen.width = Window.GetWidth();",
			"screen.height = Window.GetHeight();",
			"screen.x = Window.GetX();",
			"screen.y = Window.GetY();",
			`screen.scale = screen.width / ${REFERENCE_WIDTH};`,
			"",
			"# The field: one colour, top to bottom.",
			`Window.SetBackgroundTopColor(${floats(context, "surface.base")});`,
			`Window.SetBackgroundBottomColor(${floats(context, "surface.base")});`,
			"",
			"# The wordmark, above centre.",
			`wordmark.image = Image.Text("Arch Linux", ${floats(context, "text.primary")});`,
			"wordmark.image = wordmark.image.Scale(Math.Int(wordmark.image.GetWidth() * screen.scale),",
			"                                           Math.Int(wordmark.image.GetHeight() * screen.scale));",
			"wordmark.sprite = Sprite(wordmark.image);",
			"wordmark.sprite.SetPosition(screen.x + Math.Int((screen.width - wordmark.image.GetWidth()) / 2),",
			"                            screen.y + Math.Int(screen.height * 0.44),",
			"                            10);",
			"",
			"# The progress line: a track the accent fills as the boot runs, with a first-length nub of",
			"# the accent drawn before any progress arrives, so a fast boot never shows a bare track.",
			"line.width = Math.Int(screen.width * 0.22);",
			"line.height = Math.Int(2 * screen.scale);",
			"line.min = Math.Int(14 * screen.scale);",
			"line.x = screen.x + Math.Int((screen.width - line.width) / 2);",
			"line.y = screen.y + Math.Int(screen.height * 0.51);",
			"",
			`line.track = Image.Text("${SOLID}", 1, 1, 1, 1, "${FACE}");`,
			"line.track = line.track.Scale(line.width, line.height);",
			"line.track_sprite = Sprite(line.track);",
			"line.track_sprite.SetPosition(line.x, line.y, 10);",
			`line.track_sprite.SetOpacity(${alpha(context, "border.strong")});`,
			"",
			`line.source = Image.Text("${SOLID}", ${floats(context, "accent.primary")}, 1, "${FACE}");`,
			"line.source = line.source.Scale(line.width, line.height);",
			"line.fill = Sprite();",
			"line.fill.SetPosition(line.x, line.y, 11);",
			"line.fill.SetImage(line.source.Scale(line.min, line.height));",
			"line.fill.SetOpacity(1);",
			"line.drawn = line.min;",
			"",
			"fun draw_progress(width)",
			"  {",
			"    progress.shown = width;",
			"    if (progress.shown < line.min)",
			"        progress.shown = line.min;",
			"    if (progress.shown == line.drawn)",
			"        return;",
			"    line.drawn = progress.shown;",
			"    line.fill.SetImage(line.source.Scale(progress.shown, line.height));",
			"  }",
			"",
			"fun progress_callback(duration, progress)",
			"  {",
			"    draw_progress(Math.Int(line.width * progress));",
			"  }",
			"",
			"fun display_normal_callback()",
			"  {",
			"  }",
			"",
			"# Boot messages along the lower third, dimmer than the wordmark and never persistent.",
			"message.sprite = Sprite();",
			"message.sprite.SetOpacity(0);",
			"",
			"fun display_message_callback(text)",
			"  {",
			`    message.image = Image.Text(text, ${floats(context, "text.muted")});`,
			"    message.sprite.SetImage(message.image);",
			"    message.sprite.SetPosition(screen.x + Math.Int((screen.width - message.image.GetWidth()) / 2),",
			"                               screen.y + Math.Int(screen.height * 0.62),",
			"                               10);",
			"    message.sprite.SetOpacity(1);",
			"  }",
			"",
			"fun hide_message_callback(text)",
			"  {",
			"    message.sprite.SetOpacity(0);",
			"  }",
			"",
			"# The passphrase dialog, for the case where the key on the initramfs does not open the",
			"# root volume and plymouth has to ask. Bullets stand in for the entry itself, which the",
			"# script plugin cannot draw.",
			"dialog.capacity = 32;",
			"dialog.prompt = Sprite();",
			"dialog.prompt.SetOpacity(0);",
			"dialog.bullet_width = Math.Int(14 * screen.scale);",
			"dialog.bullets_x = screen.x + Math.Int((screen.width - dialog.capacity * dialog.bullet_width) / 2);",
			"dialog.bullets_y = screen.y + Math.Int(screen.height * 0.55);",
			"",
			"for (index = 0; index < dialog.capacity; index++)",
			"  {",
			`    dialog.bullet[index] = Sprite(Image.Text("●", ${floats(context, "accent.primary")}, 1, "${FACE}"));`,
			"    dialog.bullet[index].SetPosition(dialog.bullets_x + index * dialog.bullet_width, dialog.bullets_y, 21);",
			"    dialog.bullet[index].SetOpacity(0);",
			"  }",
			"",
			"fun display_password_callback(prompt, bullets)",
			"  {",
			`    dialog.prompt_image = Image.Text(prompt, ${floats(context, "text.primary")});`,
			"    dialog.prompt.SetImage(dialog.prompt_image);",
			"    dialog.prompt.SetPosition(screen.x + Math.Int((screen.width - dialog.prompt_image.GetWidth()) / 2),",
			"                              screen.y + Math.Int(screen.height * 0.50),",
			"                              20);",
			"    dialog.prompt.SetOpacity(1);",
			"    for (index = 0; index < dialog.capacity; index++)",
			"      {",
			"        if (index < bullets)",
			"            dialog.bullet[index].SetOpacity(1);",
			"        else",
			"            dialog.bullet[index].SetOpacity(0);",
			"      }",
			"  }",
			"",
			"Plymouth.SetBootProgressFunction(progress_callback);",
			"Plymouth.SetDisplayNormalFunction(display_normal_callback);",
			"Plymouth.SetDisplayMessageFunction(display_message_callback);",
			"Plymouth.SetHideMessageFunction(hide_message_callback);",
			"Plymouth.SetDisplayPasswordFunction(display_password_callback);",
		]
		return `${lines.join("\n")}\n`
	},
}
