/**
 * colors.template.ts — the palette for tmux, rendered to colors.conf.
 *
 * tmux reads an additional config with `source-file`, so this file holds the
 * colour settings only: styles, borders and the message line. Every value is a
 * token's colour, named for the part it plays rather than for the colour it is.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template colors.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ].join("\n")
}

function solid(context: Context, name: string): string {
  const token = context.palette.find(name)
  const value = token.solid ?? token.hex
  if (value === undefined) throw new Error(`${name} carries no colour`)
  return value
}

const SETTINGS: [string, string, string][] = [
  ["status-style", "text.muted", "surface.base"],
  ["status-left-style", "accent.primary", "surface.base"],
  ["status-right-style", "text.muted", "surface.base"],
  ["window-status-style", "text.muted", "surface.base"],
  ["window-status-current-style", "text.strong", "surface.raised"],
  ["window-status-activity-style", "state.warning", "surface.base"],
  ["message-style", "text.primary", "surface.raised"],
  ["message-command-style", "text.primary", "surface.raised"],
  ["pane-border-style", "text.faint-solid", ""],
  ["pane-active-border-style", "accent.primary", ""],
  ["mode-style", "text.on-accent", "accent.primary"],
  ["copy-mode-match-style", "text.on-accent", "accent.primary"],
  ["copy-mode-current-match-style", "text.on-accent", "accent.soft"],
  ["clock-mode-colour", "accent.primary", ""],
]

export default {
  render(context: Context): string {
    const lines = [header(context)]
    for (const [setting, foreground, background] of SETTINGS) {
      const style = background === "" ? `fg=${solid(context, foreground)}` : `fg=${solid(context, foreground)},bg=${solid(context, background)}`
      lines.push(`set -g ${setting} "${style}"`)
    }
    return `${lines.join("\n")}\n`
  },
}
