/**
 * palette.gen.template.ts — the palette for GTK4 and libadwaita apps, rendered
 * to palette.gen.css.
 *
 * The libadwaita names are the sanctioned seam, so they keep their upstream
 * spelling; libadwaita defines no success colour and no wash, so the values it
 * has no key for carry the same `ags_` prefix the GTK3 stylesheets use. GTK4 CSS
 * is imported rather than namespaced, so these names are global to the app that
 * imports the file.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  colour: { parseHex(hex: string): { r: number; g: number; b: number }; formatAlpha(alpha: number): string }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "/* Generated by house-palette from the house palette — do not edit by hand.",
    `   palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `   template palette.gen.template.ts, sha256 ${provenance.template.sha256}`,
    "   Re-render with .github/scripts/palette-check.sh --render; see the README. */",
    "",
  ].join("\n")
}

function colour(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.hex === undefined) throw new Error(`${name} carries no colour`)
  if (token.alpha === undefined) return token.hex
  const { r, g, b } = context.colour.parseHex(token.hex)
  return `rgba(${r}, ${g}, ${b}, ${context.colour.formatAlpha(token.alpha)})`
}

const NAMES: [string, string][] = [
  ["window_bg_color", "surface.window"],
  ["window_fg_color", "text.primary"],
  ["view_bg_color", "surface.view"],
  ["view_fg_color", "text.primary"],
  ["headerbar_bg_color", "surface.window"],
  ["headerbar_fg_color", "text.primary"],
  ["headerbar_border_color", "interaction.hover"],
  ["popover_bg_color", "surface.raised"],
  ["popover_fg_color", "text.primary"],
  ["dialog_bg_color", "surface.window"],
  ["dialog_fg_color", "text.primary"],
  ["card_bg_color", "interaction.card-wash"],
  ["card_fg_color", "text.primary"],
  ["accent_bg_color", "accent.primary"],
  ["accent_fg_color", "text.on-accent"],
  ["accent_color", "accent.primary"],
  ["destructive_bg_color", "state.error"],
  ["destructive_fg_color", "text.on-accent"],
  ["destructive_color", "state.error"],
  ["warning_bg_color", "state.warning"],
  ["warning_color", "state.warning"],
  ["borders", "border.strong"],
  ["ags_success", "state.success"],
  ["ags_accent_soft", "accent.soft"],
  ["ags_text_dim", "text.muted"],
  ["ags_text_secondary", "text.secondary"],
  ["ags_hairline", "border.hairline"],
  ["ags_hover", "interaction.hover"],
  ["ags_hover_strong", "interaction.hover-strong"],
  ["ags_wash", "interaction.wash"],
  ["ags_accent_fill", "interaction.accent-fill"],
  ["ags_focus_ring", "interaction.focus-ring"],
  ["ags_selection_row", "interaction.selection-row"],
  ["ags_row_selected", "interaction.row-selected"],
  ["ags_scrollbar_thumb", "interaction.scrollbar-thumb"],
  ["ags_scrollbar_thumb_hover", "interaction.scrollbar-thumb-hover"],
  ["ags_scrollbar_thumb_active", "interaction.scrollbar-thumb-active"],
]

export default {
  render(context: Context): string {
    const lines = [header(context)]
    for (const [name, token] of NAMES) lines.push(`@define-color ${name} ${colour(context, token)};`)
    // libadwaita resolves a backdrop colour by name, so the alias stays an alias.
    lines.push("@define-color headerbar_backdrop_color @window_bg_color;")
    return `${lines.join("\n")}\n`
  },
}
