general {
    lock_cmd = pgrep -f '[t]inshell-lock' || TINSHELL_GREETER_MODE=lock /home/tinoy/dev/tinshell/apps/greeter/dist/tinshell-lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = /home/tinoy/.local/bin/hypr-dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = /home/tinoy/.local/bin/hypr-dpms off
    on-resume = /home/tinoy/.local/bin/hypr-dpms on
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
