general {
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(32, 33, 36, 1.0)
}

label {
    monitor =
    text = $TIME12
    color = rgba(241, 243, 244, 1.0)
    font_size = 72
    font_family = Sans
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(189, 193, 198, 1.0)
    font_size = 18
    font_family = Sans
    position = 0, 84
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 360, 56
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(138, 180, 248, 1.0)
    inner_color = rgba(48, 49, 52, 1.0)
    font_color = rgba(241, 243, 244, 1.0)
    fail_color = rgba(242, 139, 130, 1.0)
    check_color = rgba(251, 188, 5, 1.0)
    placeholder_text = <i>Password</i>
    fade_on_empty = false
    rounding = 8
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = $FAIL
    color = rgba(242, 139, 130, 1.0)
    font_size = 14
    font_family = Sans
    position = 0, -52
    halign = center
    valign = center
}
