/**
 * hyprlock.colours.template.ts — the lock screen's colours, rendered to
 * hyprlock.colours.conf.
 *
 * hyprlock reads a config through `source` and expands `$name` where a value is
 * expected, so the fragment defines variables only: no widget block appears here,
 * which keeps every widget's text, position and size in hyprlock.conf where a
 * person edits them. Colours use Hyprland's `rgba(rrggbbaa)` form.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template hyprlock.colours.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ].join("\n")
}

function hypr(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.hex === undefined) throw new Error(`${name} carries no colour`)
  const alpha = token.alpha === undefined ? "ff" : Math.round(token.alpha * 255).toString(16).padStart(2, "0")
  return `rgba(${token.hex.slice(1)}${alpha})`
}

const VARIABLES: [string, string][] = [
  ["house_lock_background", "surface.window"],
  ["house_lock_input_fill", "surface.raised"],
  ["house_lock_clock", "text.strong"],
  ["house_lock_identity", "text.secondary"],
  ["house_lock_input_text", "text.primary"],
  ["house_lock_input_outline", "accent.primary"],
  ["house_lock_fail", "state.error"],
  ["house_lock_check", "state.warning"],
]

export default {
  render(context: Context): string {
    const lines = [header(context)]
    for (const [name, token] of VARIABLES) lines.push(`$${name} = ${hypr(context, token)}`)
    return `${lines.join("\n")}\n`
  },
}
