/**
 * palette.template.ts — the palette as a Lua table, rendered to palette.lua.
 *
 * Hyprland's Lua config reaches a module beside it with `require`, so the
 * compositor's own values live here and hyprland.lua reads them from it. Colours
 * are Hyprland's form, `rgba(rrggbbaa)`: the alpha byte is `ff` for a solid token
 * and the token's own alpha where it carries one. An `opacity.*` token has no
 * colour of its own and is not carried here — a surface that needs one names the
 * token it belongs to.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "-- Generated by house-palette from the house palette — do not edit by hand.",
    `-- palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `-- template palette.template.ts, sha256 ${provenance.template.sha256}`,
    "-- Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ].join("\n")
}

function hypr(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.hex === undefined) throw new Error(`${name} carries no colour`)
  const alpha = token.alpha === undefined ? "ff" : Math.round(token.alpha * 255).toString(16).padStart(2, "0")
  return `rgba(${token.hex.slice(1)}${alpha})`
}

const GROUPS: [string, [string, string][]][] = [
  [
    "Surfaces",
    [
      ["panel_base", "surface.base"],
      ["view_base", "surface.view"],
      ["window_base", "surface.window"],
      ["surface_raised", "surface.raised"],
      ["input_panel_base", "surface.input"],
    ],
  ],
  [
    "Text",
    [
      ["text_on_accent", "text.on-accent"],
      ["text_strong", "text.strong"],
      ["text_primary", "text.primary"],
      ["text_secondary", "text.secondary"],
      ["text_muted", "text.muted"],
      ["text_faint", "text.faint"],
    ],
  ],
  [
    "Accents",
    [
      ["accent", "accent.primary"],
      ["accent_soft", "accent.soft"],
      ["accent_secondary", "accent.secondary"],
      ["accent_tertiary", "accent.tertiary"],
    ],
  ],
  [
    "States",
    [
      ["error", "state.error"],
      ["warning", "state.warning"],
      ["success", "state.success"],
    ],
  ],
  [
    "Borders",
    [
      ["border_active", "border.active"],
      ["border_inactive", "border.inactive"],
      ["border_hairline", "border.hairline"],
      ["border_strong", "border.strong"],
    ],
  ],
  [
    "Fills",
    [
      ["hover", "interaction.hover"],
      ["hover_strong", "interaction.hover-strong"],
      ["wash", "interaction.wash"],
      ["card_wash", "interaction.card-wash"],
      ["selection_menu", "interaction.selection-menu"],
      ["selection_row", "interaction.selection-row"],
      ["selection_text", "interaction.selection-text"],
      ["accent_fill", "interaction.accent-fill"],
      ["focus_ring", "interaction.focus-ring"],
      ["danger_fill", "interaction.danger-fill"],
      ["row_highlight", "interaction.row-highlight"],
      ["row_active", "interaction.row-active"],
      ["row_selected", "interaction.row-selected"],
    ],
  ],
  ["Effects", [["text_shadow", "effect.text-shadow"]]],
]

export default {
  render(context: Context): string {
    const lines = [header(context), "return {"]
    GROUPS.forEach(([label, group], index) => {
      lines.push(`    -- ${label}`)
      for (const [key, token] of group) lines.push(`    ${key} = "${hypr(context, token)}",`)
      if (index < GROUPS.length - 1) lines.push("")
    })
    lines.push("}")
    return `${lines.join("\n")}\n`
  },
}
