-- Generated by house-palette from the house palette — do not edit by hand.
-- palette 04031d0, sha256 15322952c371949710ae4648cc4e1feb64c5ff750451bc8f85113e1aa3b2127a
-- template palette.template.ts, sha256 90090a7fd8b5d8d29e2e7632f2461bc46a8d58706fa6a47ebe4fac7b8c9de5ef
-- Re-render with .github/scripts/palette-check.sh --render; see the README.

return {
    -- Surfaces
    panel_base = "rgba(0a0c11ff)",
    view_base = "rgba(16181cff)",
    window_base = "rgba(1b1d22ff)",
    surface_raised = "rgba(23262cff)",
    input_panel_base = "rgba(171a21ff)",

    -- Text
    text_on_accent = "rgba(14171cff)",
    text_strong = "rgba(ffffffff)",
    text_primary = "rgba(e6e6e6ff)",
    text_secondary = "rgba(c9c9c9ff)",
    text_muted = "rgba(a6a6a6ff)",
    text_faint = "rgba(a6a6a68c)",

    -- Accents
    accent = "rgba(8ab5f7ff)",
    accent_soft = "rgba(adcbf9ff)",
    accent_secondary = "rgba(4cccf2ff)",
    accent_tertiary = "rgba(b88cf2ff)",

    -- States
    error = "rgba(ff6b6bff)",
    warning = "rgba(f0b35aff)",
    success = "rgba(8af7aeff)",

    -- Borders
    border_active = "rgba(ccccccff)",
    border_inactive = "rgba(00000000)",
    border_hairline = "rgba(ffffff0f)",
    border_strong = "rgba(ffffff1a)",

    -- Fills
    hover = "rgba(ffffff14)",
    hover_strong = "rgba(ffffff24)",
    wash = "rgba(ffffff1a)",
    card_wash = "rgba(ffffff0d)",
    selection_menu = "rgba(8ab5f738)",
    selection_row = "rgba(8ab5f759)",
    selection_text = "rgba(8ab5f773)",
    accent_fill = "rgba(8ab5f72e)",
    focus_ring = "rgba(8ab5f78c)",
    danger_fill = "rgba(ff6b6b29)",
    row_highlight = "rgba(ffffff1a)",
    row_active = "rgba(ffffff29)",
    row_selected = "rgba(0a0c11b8)",

    -- Effects
    text_shadow = "rgba(00000070)",
}
