/**
 * gtkrc.house.template.ts — the palette for GTK2 apps, rendered to .config/gtkrc.house.
 *
 * GTK2's rc parser has no symbolic colour definition, so the palette enters
 * through `gtk_color_scheme`: the setting GTK2 applications read for their
 * default colours. That scheme carries no alpha, so every value here is the
 * token's solid form. GTK2 is not installed on this machine, so the fragment is
 * unverified at runtime; it is read the next time a GTK2 application starts.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template gtkrc.house.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ].join("\n")
}

function solid(context: Context, name: string): string {
  const token = context.palette.find(name)
  const value = token.solid ?? token.hex
  if (value === undefined) throw new Error(`${name} carries no colour`)
  return value
}

const KEYS: [string, string][] = [
  ["fg_color", "text.primary"],
  ["bg_color", "surface.base"],
  ["base_color", "surface.view"],
  ["text_color", "text.primary"],
  ["selected_bg_color", "accent.primary"],
  ["selected_fg_color", "text.on-accent"],
  ["tooltip_bg_color", "surface.raised"],
  ["tooltip_fg_color", "text.primary"],
  ["link_color", "accent.primary"],
  ["link_visited_color", "accent.tertiary"],
  ["error_color", "state.error"],
  ["warning_color", "state.warning"],
]

export default {
  render(context: Context): string {
    const entries = KEYS.map(([key, token]) => `${key}:${solid(context, token)}`)
    return `${header(context)}gtk_color_scheme = "${entries.join("\n")}"\n`
  },
}
