/**
 * palette.gen.template.ts — the palette for GTK3 apps, rendered to palette.gen.css.
 *
 * GTK3 CSS is imported, not included into a namespace, so every name here is
 * global to the application that imports it: the stylesheets beside this file
 * read these names, and the hand-copied `@define-color` block they used to carry
 * is gone. A name whose value is translucent is written as `rgba()`, because GTK3
 * reads a colour with an alpha channel; `solid` names take the token's hex.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  colour: { parseHex(hex: string): { r: number; g: number; b: number }; formatAlpha(alpha: number): string }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "/* Generated by house-palette from the house palette — do not edit by hand.",
    `   palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `   template palette.gen.template.ts, sha256 ${provenance.template.sha256}`,
    "   Re-render with .github/scripts/palette-check.sh --render; see the README. */",
    "",
  ].join("\n")
}

function colour(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.hex === undefined) throw new Error(`${name} carries no colour`)
  if (token.alpha === undefined) return token.hex
  const { r, g, b } = context.colour.parseHex(token.hex)
  return `rgba(${r}, ${g}, ${b}, ${context.colour.formatAlpha(token.alpha)})`
}

const NAMES: [string, string][] = [
  ["ags_surface", "surface.window"],
  ["ags_surface_raised", "surface.raised"],
  ["ags_view", "surface.view"],
  ["ags_text", "text.primary"],
  ["ags_text_emphasised", "text.strong"],
  ["ags_text_secondary", "text.secondary"],
  ["ags_text_dim", "text.muted"],
  ["ags_ink_faint", "text.faint"],
  ["ags_accent", "accent.primary"],
  ["ags_accent_soft", "accent.soft"],
  ["ags_ink_on_accent", "text.on-accent"],
  ["ags_danger", "state.error"],
  ["ags_warning", "state.warning"],
  ["ags_success", "state.success"],
  ["ags_hairline", "border.hairline"],
  ["ags_border_strong", "border.strong"],
  ["ags_hover", "interaction.hover"],
  ["ags_hover_strong", "interaction.hover-strong"],
  ["ags_wash", "interaction.wash"],
  ["ags_card_wash", "interaction.card-wash"],
  ["ags_accent_fill", "interaction.accent-fill"],
  ["ags_danger_fill", "interaction.danger-fill"],
  ["ags_focus_ring", "interaction.focus-ring"],
  ["ags_selection_menu", "interaction.selection-menu"],
  ["ags_selection_row", "interaction.selection-row"],
  ["ags_row_selected", "interaction.row-selected"],
  ["ags_scrollbar_thumb", "interaction.scrollbar-thumb"],
  ["ags_scrollbar_thumb_hover", "interaction.scrollbar-thumb-hover"],
  ["ags_scrollbar_thumb_active", "interaction.scrollbar-thumb-active"],
  ["ags_shadow", "effect.text-shadow"],
]

export default {
  render(context: Context): string {
    const lines = [header(context)]
    for (const [name, token] of NAMES) lines.push(`@define-color ${name} ${colour(context, token)};`)
    return `${lines.join("\n")}\n`
  },
}
