/**
 * colors.template.ts — the palette for git's own output, rendered to colors.inc.
 *
 * git reads a secondary config through `include.path`, so this file is a config
 * fragment holding `[color "..."]` sections and nothing else. Every value is a
 * token's colour: git's colour names are its own vocabulary, and a house token is
 * chosen for the job the name does.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "# Generated by house-palette from the house palette — do not edit by hand.",
    `# palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `# template colors.template.ts, sha256 ${provenance.template.sha256}`,
    "# Re-render with .github/scripts/palette-check.sh --render; see the README.",
    "",
  ].join("\n")
}

function solid(context: Context, name: string): string {
  const token = context.palette.find(name)
  const value = token.solid ?? token.hex
  if (value === undefined) throw new Error(`${name} carries no colour`)
  return value
}

const SECTIONS: [string, [string, string][]][] = [
  [
    "status",
    [
      ["added", "state.success"],
      ["changed", "state.warning"],
      ["untracked", "text.muted"],
    ],
  ],
  [
    "branch",
    [
      ["current", "accent.primary"],
      ["local", "text.primary"],
      ["remote", "accent.tertiary"],
    ],
  ],
  [
    "diff",
    [
      ["meta", "text.muted"],
      ["frag", "accent.secondary"],
      ["func", "accent.primary"],
      ["old", "state.error"],
      ["new", "state.success"],
      ["oldMoved", "state.error"],
      ["newMoved", "state.success"],
      ["context", "text.secondary"],
      ["whitespace", "state.warning"],
    ],
  ],
  [
    "decorate",
    [
      ["HEAD", "accent.soft"],
      ["branch", "accent.primary"],
      ["remoteBranch", "accent.tertiary"],
      ["tag", "state.warning"],
    ],
  ],
  [
    "grep",
    [
      ["match", "accent.primary"],
      ["context", "text.secondary"],
      ["selected", "accent.soft"],
    ],
  ],
  [
    "interactive",
    [
      ["added", "state.success"],
      ["changed", "state.warning"],
      ["untracked", "text.muted"],
    ],
  ],
]

export default {
  render(context: Context): string {
    const lines = [header(context)]
    SECTIONS.forEach(([section, keys], index) => {
      lines.push(`[color "${section}"]`)
      for (const [key, token] of keys) lines.push(`\t${key} = ${solid(context, token)}`)
      if (index < SECTIONS.length - 1) lines.push("")
    })
    return `${lines.join("\n")}\n`
  },
}
