/**
 * theme.template.ts — the GRUB menu as the house palette, rendered to theme.txt.
 *
 * This theme is drawn only when GRUB displays its menu, and this machine's menu is hidden
 * behind a zero-second timeout: grub's own run_menu() returns the default entry without
 * calling menu_init() when the timeout is 0, so the file below is loaded and left dormant
 * on a normal boot, and appears only when the menu is interrupted for — hold Escape while
 * the firmware hands over. It carries no image: the field is a colour and the entries are
 * text. Its font is the one the machine generates for the menu screen (`house-32.pf2`,
 * written by house-boot-refresh into the ESP and named as GRUB_FONT so the same face also
 * draws GRUB's own terminal, which is where a passphrase prompt is asked). A GRUB theme
 * colour has no alpha channel, so a translucent token is taken at its declared stand-in
 * rather than at its own hex.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
	palette: { find(name: string): Token }
	provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

/**
 * The font grub-mkconfig loads into the menu, named as the font file names itself. The
 * name is the one grub-mkfont stamps on house-32.pf2 for `House Boot` at size 32, and
 * house-boot-refresh refuses to install the menu unless the file carries it.
 */
const MENU_FONT = "House Boot Regular 32"

/** A token's colour for a carrier that has no alpha: its declared stand-in. */
function solid(context: Context, name: string): string {
	const value = context.palette.find(name).solid
	if (value === undefined) throw new Error(`${name} carries no colour to paint with`)
	return value
}

function header(context: Context): string {
	const { palette, template } = context.provenance
	return [
		"# Generated by colourway from the house palette — do not edit by hand.",
		`# palette ${palette.revision}, sha256 ${palette.sha256}`,
		`# template theme.template.ts, sha256 ${template.sha256}`,
		"# Re-render with .github/scripts/palette-check.sh --render; see the README.",
		"",
	].join("\n")
}

export default {
	render(context: Context): string {
		const lines = [
			header(context),
			"# The field the menu is drawn on, and the one font grub-mkconfig has loaded.",
			`desktop-color: "${solid(context, "surface.base")}"`,
			'title-text: ""',
			`terminal-font: "${MENU_FONT}"`,
			"",
			"# The entries: unselected is body text, the selection is the accent.",
			"+ boot_menu {",
			"\tleft = 25%",
			"\twidth = 50%",
			"\ttop = 35%",
			"\theight = 30%",
			`\titem_font = "${MENU_FONT}"`,
			`\titem_color = "${solid(context, "text.primary")}"`,
			`\tselected_item_color = "${solid(context, "accent.primary")}"`,
			"\titem_height = 40",
			"\titem_spacing = 8",
			"\titem_padding = 0",
			"}",
			"",
			"# The countdown, drawn as a hairline under the entries.",
			"+ progress_bar {",
			'\tid = "__timeout__"',
			"\tleft = 25%",
			"\ttop = 72%",
			"\twidth = 50%",
			"\theight = 2",
			`\tfont = "${MENU_FONT}"`,
			`\ttext_color = "${solid(context, "text.muted")}"`,
			`\tfg_color = "${solid(context, "accent.primary")}"`,
			`\tbg_color = "${solid(context, "border.hairline")}"`,
			'\ttext = "@TIMEOUT_NOTIFICATION_LONG@"',
			"}",
			"",
			"# The key hints along the bottom edge, dimmer than the entries.",
			"+ label {",
			"\tleft = 0",
			"\ttop = 100%-44",
			"\twidth = 100%",
			"\theight = 40",
			'\talign = "center"',
			`\tfont = "${MENU_FONT}"`,
			`\tcolor = "${solid(context, "text.muted")}"`,
			'\ttext = "@KEYMAP_MIDDLE@"',
			"}",
		]
		return `${lines.join("\n")}\n`
	},
}
