/**
 * house.template.ts — the palette for the YouTube Music web view, rendered to
 * house.css.
 *
 * The player injects every path listed in its own configuration, so this file is
 * a stylesheet of variables only: the app's markup is third-party and is not
 * selected on. It is inert until its path is listed there. The `opacity.*` tokens
 * carry no colour, so they travel as their own variables.
 */

type Token = { hex?: string; alpha?: number; solid?: string }
type Context = {
  palette: { find(name: string): Token }
  colour: { parseHex(hex: string): { r: number; g: number; b: number }; formatAlpha(alpha: number): string }
  provenance: { palette: { sha256: string; revision: string }; template: { sha256: string } }
}

function header(context: Context): string {
  const { palette, provenance } = context
  return [
    "/* Generated by house-palette from the house palette — do not edit by hand.",
    `   palette ${provenance.palette.revision}, sha256 ${provenance.palette.sha256}`,
    `   template house.template.ts, sha256 ${provenance.template.sha256}`,
    "   Re-render with .github/scripts/palette-check.sh --render; see the README. */",
    "",
  ].join("\n")
}

function colour(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.hex === undefined) throw new Error(`${name} carries no colour`)
  if (token.alpha === undefined) return token.hex
  const { r, g, b } = context.colour.parseHex(token.hex)
  return `rgba(${r}, ${g}, ${b}, ${context.colour.formatAlpha(token.alpha)})`
}

function opacity(context: Context, name: string): string {
  const token = context.palette.find(name)
  if (token.alpha === undefined) throw new Error(`${name} carries no opacity`)
  return context.colour.formatAlpha(token.alpha)
}

const SURFACES: [string, string][] = [
  ["house-panel-base", "surface.base"],
  ["house-view-base", "surface.view"],
  ["house-window-base", "surface.window"],
  ["house-surface-raised", "surface.raised"],
  ["house-text-on-accent", "text.on-accent"],
]

const TEXT: [string, string][] = [
  ["house-text-strong", "text.strong"],
  ["house-text-primary", "text.primary"],
  ["house-text-secondary", "text.secondary"],
  ["house-text-muted", "text.muted"],
  ["house-text-faint", "text.faint"],
]

const ACCENTS: [string, string][] = [
  ["house-accent", "accent.primary"],
  ["house-accent-soft", "accent.soft"],
  ["house-accent-secondary", "accent.secondary"],
  ["house-accent-tertiary", "accent.tertiary"],
]

const STATES: [string, string][] = [
  ["house-error", "state.error"],
  ["house-warning", "state.warning"],
  ["house-success", "state.success"],
]

const FILLS: [string, string][] = [
  ["house-hairline", "border.hairline"],
  ["house-border-strong", "border.strong"],
  ["house-hover", "interaction.hover"],
  ["house-hover-strong", "interaction.hover-strong"],
  ["house-wash", "interaction.wash"],
  ["house-card-wash", "interaction.card-wash"],
  ["house-selection-row", "interaction.selection-row"],
  ["house-selection-text", "interaction.selection-text"],
  ["house-accent-fill", "interaction.accent-fill"],
  ["house-focus-ring", "interaction.focus-ring"],
  ["house-danger-fill", "interaction.danger-fill"],
  ["house-row-selected", "interaction.row-selected"],
]

const OPACITIES: [string, string][] = [
  ["house-opacity-panel", "opacity.panel"],
  ["house-opacity-card", "opacity.card"],
  ["house-opacity-backdrop", "opacity.backdrop"],
  ["house-opacity-menu", "opacity.menu"],
  ["house-opacity-message", "opacity.message"],
]

const GROUPS: [string, (context: Context, name: string) => string, [string, string][]][] = [
  ["Surfaces", colour, SURFACES],
  ["Text", colour, TEXT],
  ["Accents", colour, ACCENTS],
  ["States", colour, STATES],
  ["Fills and borders", colour, FILLS],
  ["Surface opacities", opacity, OPACITIES],
]

export default {
  render(context: Context): string {
    const lines = [header(context), ":root {"]
    GROUPS.forEach(([label, resolve, group], index) => {
      lines.push(`  /* ${label} */`)
      for (const [name, token] of group) lines.push(`  --${name}: ${resolve(context, token)};`)
      if (index < GROUPS.length - 1) lines.push("")
    })
    lines.push("}")
    return `${lines.join("\n")}\n`
  },
}
